<a href="https://colab.research.google.com/github/kartik7702/Practice-Projects/blob/main/Mapup_Task_2_(Q1_Q5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
file_path = '/content/dataset-3.csv'

# Read the CSV file
df = pd.read_csv(file_path)

In [ ]:
df

    id_start   id_end  distance
0    1001400  1001402       9.7
1    1001402  1001404      20.2
2    1001404  1001406      16.0
3    1001406  1001408      21.7
4    1001408  1001410      11.1
5    1001410  1001412      15.6
6    1001412  1001414      18.2
7    1001414  1001416      13.2
8    1001416  1001418      13.6
9    1001418  1001420      12.9
10   1001420  1001422       9.6
11   1001422  1001424      11.4
12   1001424  1001426      18.6
13   1001426  1001428      15.8
14   1001428  1001430       8.6
15   1001430  1001432       9.0
16   1001432  1001434       7.9
17   1001434  1001436       4.0
18   1001436  1001438       9.0
19   1001436  1001437       5.0
20   1001438  1001437       4.0
21   1001438  1001440      10.0
22   1001440  1001442       3.9
23   1001442  1001488       4.5
24   1001488  1004356       4.0
25   1004356  1004354       2.0
26   1004354  1004355       2.0
27   1004355  1001444       0.7
28   1001444  1001446       6.6
29   1001446  1001448       9.6
30   1001448  1001450      15.7
31   1001450  1001452       9.9
32   1001452  1001454      11.3
33   1001454  1001456      13.6
34   1001456  1001458       8.9
35   1001458  1001460       5.1
36   1001460  1001461      12.8
37   1001460  1001462      17.9
38   1001461  1001462       5.1
39   1001462  1001464      26.7
40   1001464  1001466       8.5
41   1001466  1001468      10.7
42   1001468  1001470      10.6
43   1001470  1001472      16.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id_start  44 non-null     int64
 1   id_end    44 non-null     int64
 2   distance  44 non-null     float64
dtypes: float64(1), int64(2)
memory usage: 1.2 KB

# Question 1: Distance Matrix Calculation

In [ ]:
def calculate_distance_matrix(df):
    """
        Calculate a distance matrix based on the dataframe, df.
        Args:
            df (pandas.DataFrame): DataFrame containing columns: ID, Start, End, Distance
        Returns:
            pandas.DataFrame: Distance matrix
        """
# Create an empty DataFrame to store the distance matrix
    unique_ids = sorted(set(df['id_start'].unique()) | set(df['id_end'].unique()))
    distance_matrix = pd.DataFrame(np.zeros((len(unique_ids), len(unique_ids))), index=unique_ids, columns=unique_ids)

# Populate the distance matrix
    for index, row in df.iterrows():
        start = row['id_start']
        end = row['id_end']
        distance = row['distance']

# Update distance values in the matrix
        distance_matrix.at[start, end] = distance
        distance_matrix.at[end, start] = distance

# Calculate cumulative distances
    for i in unique_ids:
        for j in unique_ids:
            for k in unique_ids:
                if distance_matrix.at[i, j] == 0 and i != j and i != k and j != k:
                    if distance_matrix.at[i, k] != 0 and distance_matrix.at[k, j] != 0:
                        distance_matrix.at[i, j] = distance_matrix.at[i, k] + distance_matrix.at[k, j]

# Set diagonal values to 0
    np.fill_diagonal(distance_matrix.values, 0)

    return distance_matrix

In [ ]:
# Call the function
result_df = calculate_distance_matrix(df)

# Print the result
print(result_df)

         1001400  1001402  1001404  1001406  1001408  1001410  1001412  \
1001400      0.0      9.7     29.9     45.9     67.6     78.7     94.3
1001402      9.7      0.0     20.2     55.6     77.3     88.4    104.0
1001404     29.9     20.2      0.0     16.0     97.5    108.6    124.2
1001406     45.9     55.6     16.0      0.0     21.7    124.6    140.2
1001408     67.6     77.3     97.5     21.7      0.0     11.1    161.9
1001410     78.7     88.4    108.6    124.6     11.1      0.0     15.6
1001412     94.3    104.0    124.2    140.2    161.9     15.6      0.0
1001414    112.5    122.2    142.4    158.4    180.1    191.2     18.2
1001416    125.7    135.4    155.6    171.6    193.3    204.4    220.0
1001418    139.3    149.0    169.2    185.2    206.9    218.0    233.6
1001420    152.2    161.9    182.1    198.1    219.8    230.9    246.5
1001422    161.8    171.5    191.7    207.7    229.4    240.5    256.1
1001424    173.2    182.9    203.1    219.1    240.8    251.9    267.5
1001426    191.8    201.5    221.7    237.7    259.4    270.5    286.1
1001428    207.6    217.3    237.5    253.5    275.2    286.3    301.9
1001430    216.2    225.9    246.1    262.1    283.8    294.9    310.5
1001432    225.2    234.9    255.1    271.1    292.8    303.9    319.5
1001434    233.1    242.8    263.0    279.0    300.7    311.8    327.4
1001436    237.1    246.8    267.0    283.0    304.7    315.8    331.4
1001437    242.1    251.8    272.0    288.0    309.7    320.8    336.4
1001438    246.1    255.8    276.0    292.0    313.7    324.8    340.4
1001440    256.1    265.8    286.0    302.0    323.7    334.8    350.4
1001442    260.0    269.7    289.9    305.9    327.6    338.7    354.3
1001444      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001446      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001448      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001450      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001452      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001454      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001456      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001458      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001460      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001461      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001462      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001464      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001466      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001468      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001470      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001472      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1001488    264.5    274.2    294.4    310.4    332.1    343.2    358.8
1004354      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1004355      0.0      0.0      0.0      0.0      0.0      0.0      0.0
1004356    268.5    278.2    298.4    314.4    336.1    347.2    362.8

         1001414  1001416  1001418  ...  1001462  1001464  1001466  1001468  \
1001400    112.5    125.7    139.3  ...      0.0      0.0      0.0      0.0
1001402    122.2    135.4    149.0  ...      0.0      0.0      0.0      0.0
1001404    142.4    155.6    169.2  ...      0.0      0.0      0.0      0.0
1001406    158.4    171.6    185.2  ...      0.0      0.0      0.0      0.0
1001408    180.1    193.3    206.9  ...      0.0      0.0      0.0      0.0
1001410    191.2    204.4    218.0  ...      0.0      0.0      0.0      0.0
1001412     18.2    220.0    233.6  ...      0.0      0.0      0.0      0.0
1001414      0.0     13.2    251.8  ...      0.0      0.0      0.0      0.0
1001416     13.2      0.0     13.6  ...      0.0      0.0      0.0      0.0
1001418    251.8     13.6      0.0  ...      0.0      0.0      0.0      0.0
1001420    264.7    277.9     12.9  ...      0.0      0.0      0.0      0.0
1001422    274.3    287.5    301.1  ...      0.0      0.0      0.0      0.0
1001424    285.7    298.9    312.5  ...      0.0      0.0      0.0      0.0
1001426    304.3    317.5    331.1  ...      0.0      0.0      0.0      0.0
1001428    320.1    333.3    346.9  ...      0.0      0.0      0.0      0.0
1001430    328.7    341.9    355.5  ...      0.0      0.0      0.0      0.0
1001432    337.7    350.9    364.5  ...      0.0      0.0      0.0      0.0
1001434    345.6    358.8    372.4  ...      0.0      0.0      0.0      0.0
1001436    349.6    362.8    376.4  ...      0.0      0.0      0.0      0.0
1001437    354.6    367.8    381.4  ...      0.0      0.0      0.0      0.0
1001438    358.6    371.8    385.4  ...      0.0      0.0      0.0      0.0
1001440    368.6    381.8    395.4  ...      0.0      0.0      0.0      0.0
1001442    372.5    385.7    399.3  ...      0.0      0.0      0.0      0.0
1001444      0.0      0.0      0.0  ...     98.6    125.3    133.8    144.5
1001446      0.0      0.0      0.0  ...    105.2    131.9    140.4    151.1
1001448      0.0      0.0      0.0  ...    114.8    141.5    150.0    160.7
1001450      0.0      0.0      0.0  ...    130.5    157.2    165.7    176.4
1001452      0.0      0.0      0.0  ...    140.4    167.1    175.6    186.3
1001454      0.0      0.0      0.0  ...    151.7    178.4    186.9    197.6
1001456      0.0      0.0      0.0  ...    165.3    192.0    200.5    211.2
1001458      0.0      0.0      0.0  ...    174.2    200.9    209.4    220.1
1001460      0.0      0.0      0.0  ...     17.9    206.0    214.5    225.2
1001461      0.0      0.0      0.0  ...      5.1    218.8    227.3    238.0
1001462      0.0      0.0      0.0  ...      0.0     26.7    232.4    243.1
1001464      0.0      0.0      0.0  ...     26.7      0.0      8.5    269.8
1001466      0.0      0.0      0.0  ...    232.4      8.5      0.0     10.7
1001468      0.0      0.0      0.0  ...    243.1    269.8     10.7      0.0
1001470      0.0      0.0      0.0  ...    253.7    280.4    288.9     10.6
1001472      0.0      0.0      0.0  ...    269.7    296.4    304.9    315.6
1001488    377.0    390.2    403.8  ...      0.0      0.0      0.0      0.0
1004354      0.0      0.0      0.0  ...    101.3    128.0    136.5    147.2
1004355      0.0      0.0      0.0  ...     99.3    126.0    134.5    145.2
1004356    381.0    394.2    407.8  ...    103.3    130.0    138.5    149.2

         1001470  1001472  1001488  1004354  1004355  1004356
1001400      0.0      0.0    264.5      0.0      0.0    268.5
1001402      0.0      0.0    274.2      0.0      0.0    278.2
1001404      0.0      0.0    294.4      0.0      0.0    298.4
1001406      0.0      0.0    310.4      0.0      0.0    314.4
1001408      0.0      0.0    332.1      0.0      0.0    336.1
1001410      0.0      0.0    343.2      0.0      0.0    347.2
1001412      0.0      0.0    358.8      0.0      0.0    362.8
1001414      0.0      0.0    377.0      0.0      0.0    381.0
1001416      0.0      0.0    390.2      0.0      0.0    394.2
1001418      0.0      0.0    403.8      0.0      0.0    407.8
1001420      0.0      0.0    416.7      0.0      0.0    420.7
1001422      0.0      0.0    426.3      0.0      0.0    430.3
1001424      0.0      0.0    437.7      0.0      0.0    441.7
1001426      0.0      0.0    456.3      0.0      0.0    460.3
1001428      0.0      0.0    472.1      0.0      0.0    476.1
1001430      0.0      0.0    480.7      0.0      0.0    484.7
1001432      0.0      0.0    489.7      0.0      0.0    493.7
1001434      0.0      0.0    497.6      0.0      0.0    501.6
1001436      0.0      0.0    501.6      0.0      0.0    505.6
1001437      0.0      0.0    506.6      0.0      0.0    510.6
1001438      0.0      0.0    510.6      0.0      0.0    514.6
1001440      0.0      0.0    520.6      0.0      0.0    524.6
1001442      0.0      0.0      4.5      0.0      0.0    528.5
1001444    155.1    171.1      0.0      2.7      0.7      4.7
1001446    161.7    177.7      0.0      9.3      7.3     11.3
1001448    171.3    187.3      0.0     18.9     16.9     20.9
1001450    187.0    203.0      0.0     34.6     32.6     36.6
1001452    196.9    212.9      0.0     44.5     42.5     46.5
1001454    208.2    224.2      0.0     55.8     53.8     57.8
1001456    221.8    237.8      0.0     69.4     67.4     71.4
1001458    230.7    246.7      0.0     78.3     76.3     80.3
1001460    235.8    251.8      0.0     83.4     81.4     85.4
1001461    248.6    264.6      0.0     96.2     94.2     98.2
1001462    253.7    269.7      0.0    101.3     99.3    103.3
1001464    280.4    296.4      0.0    128.0    126.0    130.0
1001466    288.9    304.9      0.0    136.5    134.5    138.5
1001468     10.6    315.6      0.0    147.2    145.2    149.2
1001470      0.0     16.0      0.0    157.8    155.8    159.8
1001472     16.0      0.0      0.0    173.8    171.8    175.8
1001488      0.0      0.0      0.0      6.0      8.0      4.0
1004354    157.8    173.8      6.0      0.0      2.0      2.0
1004355    155.8    171.8      8.0      2.0      0.0      5.4
1004356    159.8    175.8      4.0      2.0      5.4      0.0

[43 rows x 43 columns]

# Question 2: Unroll Distance Matrix

In [ ]:
def unroll_distance_matrix(df) -> pd.DataFrame:
    """
    Unroll a distance matrix to a DataFrame in the style of the initial dataset.

    Args:
        df (pandas.DataFrame)

    Returns:
        pandas.DataFrame: Unrolled DataFrame containing columns 'id_start', 'id_end', and 'distance'.
    """
    #Empty list to store unrolled data
    unrolled_data = []


    #Iteratinge over the indices and columns of the original distance matrix
    for i in df.index:
        for j in df.columns:
            if i != j:
                unrolled_data.append({'id_start': i, 'id_end': j, 'distance': df.at[i, j]})

    df = pd.DataFrame(unrolled_data)

    return df

In [ ]:
result_matrix = calculate_distance_matrix(df)
df = unroll_distance_matrix(result_matrix)
print(df)

      id_start   id_end  distance
0      1001400  1001402       9.7
1      1001400  1001404      29.9
2      1001400  1001406      45.9
3      1001400  1001408      67.6
4      1001400  1001410      78.7
...        ...      ...       ...
1801   1004356  1001470     159.8
1802   1004356  1001472     175.8
1803   1004356  1001488       4.0
1804   1004356  1004354       2.0
1805   1004356  1004355       5.4

[1806 rows x 3 columns]

# Question 3: Finding IDs within Percentage Threshold

In [ ]:
def find_ids_within_ten_percentage_threshold(df, reference_id)->pd.DataFrame():
    """
    Find all IDs whose average distance lies within 10% of the average distance of the reference ID.

    Args:
        df (pandas.DataFrame)
        reference_id (int)

    Returns:
        pandas.DataFrame: DataFrame with IDs whose average distance is within the specified percentage threshold
                          of the reference ID's average distance.
    """
    # Filter rows with id_start equal to the reference value
    reference_rows = df[df['id_start'] == reference_id]

    # Calculate the average distance for the reference value
    average_distance = reference_rows['distance'].mean()

    # Calculate the threshold range (10% of the average distance)
    threshold = 0.1 * average_distance

    # Filter id_start values within the threshold range
    within_threshold = df[(df['distance'] >= (average_distance - threshold)) & (df['distance'] <= (average_distance + threshold))]

    # Get unique id_start values within the threshold range and sort them
    result_ids = sorted(within_threshold['id_start'].unique())

    return df

In [ ]:
# Call the function
reference_id = 1
ten_percentage_threshold = find_ids_within_ten_percentage_threshold(df, reference_id)
print(ten_percentage_threshold)

      id_start   id_end  distance
0      1001400  1001402       9.7
1      1001400  1001404      29.9
2      1001400  1001406      45.9
3      1001400  1001408      67.6
4      1001400  1001410      78.7
...        ...      ...       ...
1801   1004356  1001470     159.8
1802   1004356  1001472     175.8
1803   1004356  1001488       4.0
1804   1004356  1004354       2.0
1805   1004356  1004355       5.4

[1806 rows x 3 columns]

# Question 4: Calculate Toll Rate

In [ ]:
def calculate_toll_rate(df: pd.DataFrame) -> pd.DataFrame:
    """
    Calculate toll rates for each vehicle type based on the unrolled DataFrame.

    Args:
        df (pandas.DataFrame)

    Returns:
        pandas.DataFrame
    """
    # Define rate coefficients for each vehicle type
    rate_coefficients = {'moto': 0.8, 'car': 1.2, 'rv': 1.5, 'bus': 2.2, 'truck': 3.6}

    # Iterate over the rate coefficients and add columns to the DataFrame
    for vehicle_type, rate_coefficient in rate_coefficients.items():
        # Calculate toll rates based on distance and rate coefficient
        df[vehicle_type] = df['distance'] * rate_coefficient

    return df

In [ ]:
# Call the function
df_with_toll_rates = calculate_toll_rate(df)
print(df_with_toll_rates)

      id_start   id_end  distance    moto     car      rv     bus   truck
0      1001400  1001402       9.7    7.76   11.64   14.55   21.34   34.92
1      1001400  1001404      29.9   23.92   35.88   44.85   65.78  107.64
2      1001400  1001406      45.9   36.72   55.08   68.85  100.98  165.24
3      1001400  1001408      67.6   54.08   81.12  101.40  148.72  243.36
4      1001400  1001410      78.7   62.96   94.44  118.05  173.14  283.32
...        ...      ...       ...     ...     ...     ...     ...     ...
1801   1004356  1001470     159.8  127.84  191.76  239.70  351.56  575.28
1802   1004356  1001472     175.8  140.64  210.96  263.70  386.76  632.88
1803   1004356  1001488       4.0    3.20    4.80    6.00    8.80   14.40
1804   1004356  1004354       2.0    1.60    2.40    3.00    4.40    7.20
1805   1004356  1004355       5.4    4.32    6.48    8.10   11.88   19.44

[1806 rows x 8 columns]

# Question 5: Calculate Time-Based Toll Rates

In [ ]:
from datetime import time, timedelta

In [ ]:
ten_percentage_threshold.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1806 entries, 0 to 1805
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_start    1806 non-null   int64
 1   id_end      1806 non-null   int64
 2   distance    1806 non-null   float64
 3   moto        1806 non-null   float64
 4   car         1806 non-null   float64
 5   rv          1806 non-null   float64
 6   bus         1806 non-null   float64
 7   truck       1806 non-null   float64
 8   start_time  1806 non-null   object
 9   end_time    1806 non-null   object
 10  start_day   1806 non-null   object
 11  end_day     1806 non-null   object
dtypes: float64(6), int64(2), object(4)
memory usage: 169.4+ KB

In [ ]:
import pandas as pd
from datetime import time, datetime, timedelta

def calculate_time_based_toll_rates(df: pd.DataFrame) -> pd.DataFrame:
    """
    Calculate time-based toll rates for different time intervals within a day.

    Args:
        df (pandas.DataFrame)

    Returns:
        pandas.DataFrame
    """
    # Define time ranges and corresponding discount factors
    time_ranges = [(time(0, 0), time(10, 0), 0.8),
                   (time(10, 0), time(18, 0), 1.2),
                   (time(18, 0), time(23, 59, 59), 0.8)]

    # Create a dictionary with time range and discount factor information
    time_rate_info = {(start_time, end_time): discount_factor
                      for start_time, end_time, discount_factor in time_ranges}

    # Convert 'distance' to float
    df['distance'] = df['distance'].astype(float)

    # Apply time-based toll rates to the DataFrame
    for (start_time, end_time), discount_factor in time_rate_info.items():
        mask = (df['start_time'] >= start_time) & (df['end_time'] <= end_time)
        df.loc[mask, 'distance'] *= discount_factor

    # Round 'distance' to one decimal point
    df['distance'] = df['distance'].round(1)

    # Reorder columns
    df = df[['id_start', 'id_end', 'distance', 'start_day', 'start_time', 'end_day', 'end_time', 'moto', 'car', 'rv', 'bus', 'truck']]


    return df

In [ ]:
df_with_time_based_rates = calculate_time_based_toll_rates(ten_percentage_threshold)
df_with_time_based_rates

,id_start,id_end,distance,start_day,start_time,end_day,end_time,moto,car,rv,bus,truck
0,1001400,1001402,6.2,Monday,00:09:00,Sunday,00:18:42,7.76,11.64,14.55,21.34,34.92
1,1001400,1001404,19.1,Monday,00:29:00,Sunday,00:58:54,23.92,35.88,44.85,65.78,107.64
2,1001400,1001406,29.4,Monday,00:45:00,Sunday,01:30:54,36.72,55.08,68.85,100.98,165.24
3,1001400,1001408,43.3,Monday,01:07:00,Sunday,02:14:36,54.08,81.12,101.40,148.72,243.36
4,1001400,1001410,50.4,Monday,01:18:00,Sunday,02:36:42,62.96,94.44,118.05,173.14,283.32
...,...,...,...,...,...,...,...,...,...,...,...,...
1801,1004356,1001470,102.2,Monday,02:39:00,Sunday,05:18:48,127.84,191.76,239.70,351.56,575.28
1802,1004356,1001472,112.5,Monday,02:55:00,Sunday,05:50:48,140.64,210.96,263.70,386.76,632.88
1803,1004356,1001488,2.6,Monday,00:04:00,Sunday,00:08:00,3.20,4.80,6.00,8.80,14.40
1804,1004356,1004354,1.3,Monday,00:02:00,Sunday,00:04:00,1.60,2.40,3.00,4.40,7.20
1805,1004356,1004355,3.4,Monday,00:05:00,Sunday,00:10:24,4.32,6.48,8.10,11.88,19.44